name: 🐛 Bug Report
description: Report a software bug or unexpected behavior.
title: "🐛: [TITLE]"
labels: [bug, new]
assignees:
  - alchatti
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**

  - type: checkboxes
    id: issue-check
    attributes:
      label: Preliminary Checks
      description: Please confirm the following items before submitting your bug report.
      options:
        - label: I have searched the existing issues for similar bug reports and found none.
          required: true
        - label: "I have checked 'open' AND 'closed' issues and this is not a duplicate."
          required: true

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear and concise description of what the bug is.
      placeholder: "Explain what happened..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Explain what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: '1. Go to...\n2. Click on...\n3. Scroll down to...\n4. See error'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Diagnostic Information (System Info)

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Please select your operating system.
      multiple: true
      options:
        - Android
        - iOS
        - Linux
        - MacOS
        - Windows
        - Other
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Please select your browser.
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - Other
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information / Failure Log if available
      description: Add any other context about the problem here.
      placeholder: "Any other information..."
    validations:
      required: false
