blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://docs.github.com/en/discussions
    about: Ask a question or start a general discussion before project issue is created.

  - name: ⚓ My Website & Social links
    url: https://alchatti.com
    about: Find me on other platforms
