name: 📝 Typo & Spelling Mistake Report
description: Report an issue in the project's documentation or README.md file.
title: "📝: Typo in [Location/File/Section]"
labels: [Typo, new]
assignees:
  - alchatti
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time!**

  - type: checkboxes
    id: issue-check
    attributes:
      label: Preliminary Checks
      description: Please confirm the following items before submitting your report.
      options:
        - label: "I have checked 'open' AND 'closed' and this is not a duplicate."
          required: true

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: description
    attributes:
      label: Please provide a clear and concise description of the typo or spelling mistake. If possible, suggest an alternative wording or correction.
      placeholder: "Explain what it is..."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location of the typo
      placeholder: "- File/Document Name: [e.g., README.md, CONTRIBUTING.md]\n- Section/Paragraph: [e.g., Introduction, Installation Instructions]\n- Line Number (if applicable): [e.g., Line 42]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Expected Correction
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots for this request.
    validations:
      required: false
